name: Deploy 
on: 
  
  push:
    branches: [pr,master] 
  pull_request:
    branches: [pr, master ]  
  workflow_dispatch:   
  #schedule:    
   # - cron: "*/5 * * * *"
jobs:  
  build:  
    name: Run Web App using
    runs-on: ubuntu-latest
    if: (github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/pr' || github.ref == 'refs/heads/master')
    
    container:
      image: openjdk:8-jdk-slim
    steps:
      - name: Echo 
        
        uses: actions/checkout@v1
      - run: echo "hello" 
      
  testing:
    needs: build
    runs-on: ubuntu-latest
    if: (github.event_name == 'pull_request' || github.ref == 'refs/heads/pr' || github.ref == 'refs/heads/master')

    container:
      image: openjdk:8-jdk-slim
    steps:
      - name: path 
        uses: actions/checkout@v1
      - run: pwd